@startuml

class Risk {
    coverage: Money
    deductible: Money | Percentage
    yearlyPremium: Money
    ratePremium(): Money
}

class Car extends Risk

class Home extends Risk
class InsurancePolicy {
    getPremium(): Money
}
class Carrier
class Insured {
    lastName: String
    firstName: String
}

Carrier -> InsurancePolicy
InsurancePolicy -> "M"Risk
Insured --> "M" Risk : has

InsurancePolicy - "M"Car
@enduml